# Generated by Django 5.0.2 on 2024-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_updates_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='MetaImage/'),
        ),
        migrations.AddField(
            model_name='updates',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
