# Generated by Django 5.0.2 on 2024-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_updates_meta_description_updates_meta_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('cv', models.FileField(upload_to='cv')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='annual_turnover',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='brand_handled',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='business',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='interest',
            field=models.CharField(choices=[('dealership', 'Dealership')], max_length=260),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='state',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
